Repository nizamovtimur/virtassist, pull requests merged in 2024-05, with the labels that each got.

#31 Broadcast
  admin-panel/templates/broadcast.html
  admin-panel/views.py
  chatbot/database.py
  chatbot/main.py
  docs/chatbot.md
Labels: enhancement

#30 Admin frontend
  .gitignore
  admin-panel/static/UTMN_logo_rus_wiki.svg
  admin-panel/static/styles.css
  admin-panel/templates/broadcast.html
  admin-panel/templates/danger-questions.html
  admin-panel/templates/main-page.html
  admin-panel/templates/menu.html
  admin-panel/templates/questions-analysis.html
  admin-panel/templates/questions-wo-answers.html
  admin-panel/templates/settings.html
  admin-panel/views.py
Labels: enhancement, good first issue

#35 Cluster analysis
  .env.example
  admin-panel/cluster_analysis.py
  admin-panel/config.py
  admin-panel/models.py
  admin-panel/views.py
Labels: enhancement

#37 Db migrations
  .env.example
  .gitlab-ci.yml
  adminpanel/Dockerfile
  adminpanel/auth.py
  adminpanel/cluster_analysis.py
  adminpanel/config.py
  adminpanel/models.py
  adminpanel/requirements.txt
  adminpanel/save_nltk.py
  adminpanel/static/UTMN_logo_rus_wiki.svg
  adminpanel/static/styles.css
  adminpanel/templates/broadcast.html
  adminpanel/templates/main-page.html
  adminpanel/templates/menu.html
  adminpanel/templates/questions-analysis.html
  adminpanel/templates/settings.html
  adminpanel/tests.py
  adminpanel/views.py
  adminpanel/wsgi.py
  chatbot/confluence_interaction.py
  chatbot/database.py
  db/Dockerfile-migrate
  db/alembic.ini
  db/migration/env.py
  db/migration/script.py.mako
  db/migration/versions/474ae8a7ef46_initial.py
  db/requirements.txt
  docker-compose.yml
  docs/README.md
  qa/database.py
  qa/gigachat_prompting.py
  qa/main.py
Labels: documentation, enhancement

#39 Flask login auth.
  .env.example
  .gitlab-ci.yml
  admin-panel/models.py
  adminpanel/Dockerfile
  adminpanel/cluster_analysis.py
  adminpanel/config.py
  adminpanel/models.py
  adminpanel/requirements.txt
  adminpanel/save_nltk.py
  adminpanel/static/UTMN_logo_rus_wiki.svg
  adminpanel/static/styles.css
  adminpanel/templates/broadcast.html
  adminpanel/templates/login.html
  adminpanel/templates/main-page.html
  adminpanel/templates/menu.html
  adminpanel/templates/questions-analysis.html
  adminpanel/templates/settings.html
  adminpanel/tests.py
  adminpanel/views.py
  adminpanel/wsgi.py
  chatbot/confluence_interaction.py
  chatbot/database.py
  db/Dockerfile-migrate
  db/alembic.ini
  db/migration/env.py
  db/migration/script.py.mako
  db/migration/versions/474ae8a7ef46_initial.py
  db/migration/versions/8ca184e36b11_created_column_password_hash_in_admin_.py
  db/requirements.txt
  docker-compose.admin-db.yml
  docs/README.md
  qa/database.py
  qa/gigachat_prompting.py
  qa/main.py
Labels: bug, documentation, invalid

#40 Graphics
  .gitignore
  adminpanel/cluster_analysis.py
  adminpanel/models.py
  adminpanel/static/styles.css
  adminpanel/templates/broadcast.html
  adminpanel/templates/main-page.html
  adminpanel/templates/menu.html
  adminpanel/templates/questions-analysis.html
  adminpanel/templates/settings.html
  adminpanel/views.py
Labels: invalid

#42 Remove useless code (filter clusters by len)
  adminpanel/cluster_analysis.py
Labels: bug
