Repository nizamovtimur/virtassist, pull requests merged in 2024-06, with the labels that each got.

#43 Enhance RAG
  .env.example
  README.md
  db/migration/versions/22dcc1a837cc_change_embedding_dimension_from_312_to_.py
  docs/README.md
  docs/qa.md
  qa/config.py
  qa/confluence_retrieving.py
  qa/database.py
  qa/llm_prompting.py
  qa/main.py
  qa/save_models.py
  qa/tests.py
Labels: documentation, enhancement

#48 login fix
  adminpanel/views.py
Labels: bug, enhancement

#45 Adminpanel tests
  .gitlab-ci.yml
  adminpanel/config.py
  adminpanel/models.py
  adminpanel/tests.py
  chatbot/database.py
  chatbot/tests.py
  docs/adminpanel.md
  docs/chatbot.md
  docs/qa.md
  qa/database.py
Labels: documentation, question

#49 Front fixes
  adminpanel/static/favicon.png
  adminpanel/static/noquestions.png
  adminpanel/templates/broadcast.html
  adminpanel/templates/menu.html
  adminpanel/templates/questions-analysis.html
  adminpanel/views.py
  chatbot/main.py
Labels: enhancement
